config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/home'
  get '/tax_references', to: 'tax_references#index'
  get '/tax_references/:year', to: 'tax_references#show'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :admins
  root to: "pages#home"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable, :confirmable,
         :lockable, :timeoutable, :trackable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/salary.rb
class Salary < ApplicationRecord
end

app/models/tax_reference.rb
class TaxReference < ApplicationRecord
  default_scope { order(year: :desc) }
  validates :year, uniqueness: true
  MAX_MONTHLY_HOURS = 172

  def worker_contribution(number_of_hours)
    return self.hourly_wage * number_of_hours * self.worker_percentage / 100
  end

  def employer_contribution(number_of_hours)
    return self.hourly_wage * number_of_hours * self.employer_percentage / 100
  end

  def total_contribution(number_of_hours)
    return self.employer_contribution(number_of_hours) +
        self.worker_contribution(number_of_hours)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :lockable, :timeoutable, :trackable, :omniauthable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tax_references_controller.rb
class TaxReferencesController < ApplicationController
  def index
    @tax_references = TaxReference.all
  end

  def show
    @tax_references = TaxReference.all
    @tax_reference = TaxReference.find_by(year: params[:year])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tax_references_helper.rb
module TaxReferencesHelper
end

app/views/layouts/_content.html.erb
<main role="main" class="flex-shrink-0">
  <div class="container text-center">
    <%= yield %>
  </div>
</main>

app/views/layouts/_footer.html.erb
<footer class="footer py-3 fixed-bottom">
  <div class="container">
    <span class="text-muted">Place sticky footer content here.</span>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= render 'layouts/top_navigation' %>
</header>

app/views/layouts/_toasts.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
      <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      toastr['<%= type %>']('<%= f[1] %>');
      <% end %>
  </script>
<% end %>

app/views/layouts/_top_navigation.html.erb
<!-- Sticky navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to(t('Home'), root_path, class: 'nav-link') %>
      </li>
      <li class="nav-item">
        <%= link_to(t('Tax References Tables'), tax_references_path, class: 'nav-link') %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Admin", rails_admin_path, class: 'nav-link' %>
        </li>
      </ul>
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render 'layouts/toasts' %>
  <%= render 'layouts/header' %>
  <%= render 'layouts/content' %>
  <%= render 'layouts/footer' %>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/tax_references/_top_list.html.erb
<ul class="nav nav-tabs" role="tablist">
  <% tax_references.each do |tax_ref| %>
    <li class="nav-item">
      <% item_class = 'nav-link' %>
      <% if not @tax_reference.nil? and tax_ref.year == @tax_reference.year %>
        <% item_class.concat(' active') %>
      <% end %>

      <%= link_to tax_ref.year, {controller: 'tax_references', action: :show, year: tax_ref.year},
                  class: item_class %>
    </li>
  <% end %>
</ul>

app/views/tax_references/index.html.erb
<%= render 'top_list', tax_references: @tax_references %>

app/views/tax_references/show.html.erb
<%= render 'top_list', tax_references: @tax_references %>

<p><%= @tax_reference.year %></p>
<p><%= @tax_reference.hourly_wage %></p>
<p><%= number_to_percentage(@tax_reference.worker_percentage, precision: 2) %></p>
<p><%= number_to_percentage(@tax_reference.employer_percentage, precision: 2) %></p>

<table class="table">
  <thead>
  <tr>
    <th scope="col"><%= t('Number of Hours') %></th>
    <th scope="col"><%= t('Employer (extra)') %></th>
    <th scope="col"><%= t('Worker (discount)') %></th>
    <th scope="col"><%= t('Total contribution') %></th>
  </tr>
  </thead>
  <tbody>
  <% hourly_contribution = @tax_reference.hourly_wage / 100 %>
  <% (@tax_reference.min_monthly_hours..TaxReference::MAX_MONTHLY_HOURS).each do |n_hours| %>
    <tr>
      <td scope="row"><%= n_hours %></td>
      <td><%= number_to_currency(@tax_reference.employer_contribution(n_hours), locale: :pt) %></td>
      <td><%= number_to_currency(@tax_reference.worker_contribution(n_hours), locale: :pt) %></td>
      <td><%= number_to_currency(@tax_reference.total_contribution(n_hours), locale: :pt) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>